name: Build and Deploy artifacts

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: cat /home/runner/.m2/settings.xml
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -U -Pnative -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay
        uses: docker/login-action@v1.12.0
        with:
          registry: 'quay.io'
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Set Mercury Version
        run: |
          echo "MERCURY_VERSION=xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml" >> $GITHUB_ENV
      - name: Build and publish mercury-operator container image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./mercury-operator
          push: true
          tags: ${{ env.MERCURY_VERSION }}