name: Build and Deploy artifacts

on:
  push:
    branches:
      - main

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install xmllint
        run: |
          sudo apt-get install libxml2-utils
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -Pnative -DskipTests -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=150
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Mercury Version
        run: |
          echo "MERCURY_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)" >> $GITHUB_ENV
      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2.5.1
        with:
          tags: quay.io/ecosystem-appeng/mercury-operator:${{ env.MERCURY_VERSION }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}