apiVersion: mercury.redhat.io/v1alpha1
kind: ServiceDomain
metadata:
  name: party-routing-profile
  labels:
    service-domain: party-routing-profile
spec:
  businessImage: quay.io/ecosystem-appeng/party-routing-profile-example:1.0.1-SNAPSHOT
  serviceDomainCluster: service-domain-cluster
  type: PartyRoutingProfile
  expose:
    - http